FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    netcat-openbsd \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

# DO NOT copy project files
# Code will be mounted as a volume
COPY ./wait-for-db.sh /wait-for-db.sh
RUN chmod +x /wait-for-db.sh

COPY ./entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh




ENTRYPOINT ["/entrypoint.sh"]
CMD ["gunicorn", "EventHub.wsgi:application", "--bind", "0.0.0.0:8000", "--reload", "--workers", "3"]